### ISSUE TITLE
Issues persist after mod is removed

### ISSUE THREAD

**Issue by DiabloFan8675309** [skythebro/V-Comforts#4]
Tried VComfort today, seemed fine on the local server. I put it on the main server and issues with bags and stacks not working correctly when these settings were set to false. We were only trying out the fishing part that did work. I decided to remove this mod because of the issues. Server was shut down, files were removed and restarted.

However, even after removing this mod we are still experiencing stack issues. The screenshot was a stack of 2k stone. I split this and got 2 piles of 1k stone. When I split the same stack I got 2 piles of 500. I can move this pile and it tries to split it when all I want to do is move it.

When I split the second stack of 1000 and so on I get a bunch of 20 in a stack

I am not sure what to do to fix this.

![Image](https://github.com/user-attachments/assets/abba9e71-016b-4491-8776-f169b017cad9)

![Image](https://github.com/user-attachments/assets/3c88ef04-0c15-45a4-bf3a-094c7b326605)

**Comment by DiabloFan8675309** [comment]
Video about it here

https://streamable.com/s4wrip

**Comment by DiabloFan8675309** [comment]
![Image](https://github.com/user-attachments/assets/9457f052-40fe-4f9c-9b66-3e799df2cbfc)

**Comment by DiabloFan8675309** [comment]
There are also a lot of other issues going on now too for everyone, blood potions disappearing or turning into a nothing like this

![Image](https://github.com/user-attachments/assets/10110cc6-2676-448d-9be4-c1b0c2ccba6f)

**Comment by SkyKDG** [comment]
Thank you for reporting, I don't know how but somehow I missed this but some patches don't have the enabled check in them which causes it to be enabled all the time. I've also experienced the bug you've experienced where it splits the stack across the whole inventory and will look to fix this.

Lastly the blood potions losing their data should not occur anymore in version 0.0.4, but if it is still the case feel free to provide more information on when it occurs!

**Comment by SkyKDG** [comment]
I also didn't think about a reset that makes sure the inventory is back to normal. This will be implemented in the next version alongside with the other fixes.

**Comment by DiabloFan8675309** [comment]
Thank you so much, everyone here is looking forward to the update!

The blood potion issue is still happening with the latest release. I had issues taking blood potions out of the best, notice some were disappearing. After combining a blood potion and having a spare one in my inventory shortly after the spare one turned into the no name blood one.

When another player experienced this they dropped the potion on the ground and got two.

**Comment by DiabloFan8675309** [comment]
https://github.com/user-attachments/assets/f9cd8637-b90c-418e-8bbd-e37a3df37a3e

Here is a video on the potions as well.

**Comment by SkyKDG** [comment]
> Thank you so much, everyone here is looking forward to the update!
> 
> The blood potion issue is still happening with the latest release. I had issues taking blood potions out of the best, notice some were disappearing. After combining a blood potion and having a spare one in my inventory shortly after the spare one turned into the no name blood one.
> 
> When another player experienced this they dropped the potion on the ground and got two.

This means that somehow the stack sizes still get increased for potions as well even after I added a check for it, Ill have to look into that as well then!

**Comment by SkyKDG** [comment]
Lastly I just noticed that the splitting issue only occurs on the first slot of the inventory is this always the case? Splitting it in any other slot will work fine? 

When splitting in the first slot it causes the inventory to be fully filled up, the game then deletes the excess instead of dropping it on the ground. I'm going to do some analysis to see if it is an issue with my code or the game. If its a game issue I may need to make a custom splitting override, but we'll see if it comes to it. The splitting bug seems to split the remaining other half into (max stack size / 100) per slot. Ill have to investigate that further

**Comment by DiabloFan8675309** [comment]
I noticed this happening in other slots, not just the first one. People have also said they have issues with potions in the last slot on the action bar but work fine in others.

**Comment by SkyKDG** [comment]
Ok thanks for the info!

**Comment by SkyKDG** [comment]
What I just saw was that the issue occurs if there is an item to the left of the item you want to split, except for in the slat slot where it doesn't occur... hmm

**Comment by SkyKDG** [comment]
But It doesn't happen all the time like if I put fiber to the left of bones it's fine but if I put a consumable to the left of it it also breaks

**Comment by SkyKDG** [comment]
Think I'm onto something if a consumable if to the left of an item, that splitting issue occurs, like in your video you have potions in the last slot of your hotbar, the next slot is the first slot "in" the inventory which then causes the splitting issue?

**Comment by DiabloFan8675309** [comment]
Hope this helps

![Image](https://github.com/user-attachments/assets/25c5b674-4f03-40f3-9a25-aebaee999429)

![Image](https://github.com/user-attachments/assets/f220c64b-29a4-429b-837d-377496088d71)

**Comment by DiabloFan8675309** [comment]
Keep in mind, all these issues are still happening after the mod was removed. When you said the below, this needs to happen for all aspects of the mod. 

"I also didn't think about a reset that makes sure the inventory is back to normal. This will be implemented in the next version alongside with the other fixes."

Some folks are also saying they tried to fish10+ times and get nothing.

edit: fix to fish typo ^

**Comment by SkyKDG** [comment]
I've had a report on the fishing issue but I'm still not sure when it occurs, as I haven't experienced it yet. So will have to dig in to that.

**Comment by SkyKDG** [comment]
I fixed the splitting issue and now dragging any item onto a consumable will actually swap it as well, for some odd reason setting the max stack override causes all of these issues, I kept it in as a failsafe for if my new method of changing stacksizes didn't work but apparently the game doesn't like the overrides

**Comment by SkyKDG** [comment]
I'm releasing a new version soon, hopefully this fixes all the issues! As I cannot reproduce any of the issues stated above now after changing the code. Quickly looking at the level bonus as there seem to be issues with the equip and unequip patches

**Comment by SkyKDG** [comment]
Should be fixed!

**Comment by DiabloFan8675309** [comment]
After installing the mod, loading the game I shut the server off. Removed the mod and still issues persist. Noticed right away the split stack issue was happening.

**Comment by SkyKDG** [comment]
The mod needs to at least run once to fix all the issues. Nothing needs to be enabled but it does need to do it. Did this happen? I think this also needs to happen for each player. So to fix each player should log in while the mod is installed on the server, everything can be disabled and such but it just needs to run and then when a player joins it resets all the data back to normal. 

Can you confirm this happened?

**Comment by DiabloFan8675309** [comment]
Ill reinstall the mod shortly and have everyone test things out with it installed. Nothing should be happening with things disabled with it installed. I will update you soon.

**Comment by DiabloFan8675309** [comment]
I reinstalled the mod and it made it worse. Cant put anything in your inventory now with the mod on. I tried running the mod with default config settings enabled and then with everything off. Each time same result. Cannot move anything from storage to your inventory.

**Comment by DiabloFan8675309** [comment]
Now that this has been removed, we're encountering new issues. What can we do to get this off the server? We've been dealing with an overwhelming number of problems, players are frustrated, items are being lost, and the situation is becoming chaotic.

https://github.com/user-attachments/assets/1eca501c-d6f3-42ca-87a1-8abfa2cfe00c

**Comment by DiabloFan8675309** [comment]
All the chests are eating nothing and no longer work too

![Image](https://github.com/user-attachments/assets/838bfcbc-2c88-464a-ae44-bbee871b49a9)

**Comment by DiabloFan8675309** [comment]
Also noticing vendor issues. Buying blue weapons with t1 shards, vendor takes the shards and we get one weapon. We found out after that the weapons were stacked on top of each other.

**Comment by DiabloFan8675309** [comment]
Did some more testing, it seems like the older version of the mod does something to the save file and the new version of the mod does not correct this. That is the missing piece of the puzzle that needs to be fixed.

Put the old version of the mod that broke the online server and put it back on the local server. Confirmed things were not working. Replaced mod with the new update and confirmed things are still broken.

New world save - use the new updated mod and confirmed things are working as intended. No inventory split stack issues, fishing works etc.

**Comment by SkyKDG** [comment]
All these issues you're describing are very weird, my mod should not change any of those things. Anyway, Is there any possibility you can send over the server save file so I can have a look? As well as the modlist you're using? Also do you have the bepinex log? With all of these I can maybe figure out what is going on. Ill be using a debug version of my mod to see if why or if it's actually causing all that behaviour.

Thank you for keeping me updated.

**Comment by DiabloFan8675309** [comment]
After testing to replicate the issue, we have confirmed the following steps reliably reproduce the problem:

Set up a clean local server with these mods:
ServerLaunchFix 0.2.0
VampireCommandFramework 0.10.2
VAMP 1.1.0
VComforts 0.0.4

Load into the game and observe the issues occurring.

Replace VComforts 0.0.4 with the latest version (VComforts 0.1.0) and confirm that the problems persist.

While the fix in version 0.1.0 works fine on a fresh save, it does not resolve the issues for saves that previously used VComforts 0.0.4. We need a solution that also applies to these existing saves.

Here are the log files and video of for VComforts 0.0.4 

VComforts 0.4.0 new save starting with broken version: https://streamable.com/zf4dar
VComforts 0.1.0 same save used for VComforts 0.4.0 but now updated to latest version: https://streamable.com/qa2jq3
VComforts 0.1.0 new save: https://streamable.com/jrtz59

[LogOutput With VComfort 0.0.4 Version.log](https://github.com/user-attachments/files/20506241/LogOutput.With.VComfort.0.0.4.Version.log)

[LogOutput With VComfort 0.1.0 Version same save.log](https://github.com/user-attachments/files/20506243/LogOutput.With.VComfort.0.1.0.Version.same.save.log)

[LogOutput With VComfort 0.1.0 Version new save.log](https://github.com/user-attachments/files/20506246/LogOutput.With.VComfort.0.1.0.Version.new.save.log)

**Comment by SkyKDG** [comment]
Seems like you're sending me the client logs and not the server logs.
This is probably because of serverlaunchfix.

Because the logs state the following:
`[Warning: VComforts] This plugin is a server-only plugin!`

Can you go to the `VRising\VRising_Server\BepInEx\LogOutput.log` and give me that one? If it exists?

EDIT: with serverlaunch fix the log is located in: `VRising\BepInEx_Server\LogOutput.log`

**Comment by DiabloFan8675309** [comment]
With the local server, files from "VRising\BepInEx" are copied over to  "VRising\BepInEx_Server". The same logoutput files are there but with the BepinEx_Server tag at the top. However, I redid the test just incase I am missing something here with new log files for you.

[LogOutput With VComfort 0.0.4 Version.log](https://github.com/user-attachments/files/20507028/LogOutput.With.VComfort.0.0.4.Version.log)

[LogOutput With VComfort 0.1.0 Version same save.log](https://github.com/user-attachments/files/20507046/LogOutput.With.VComfort.0.1.0.Version.same.save.log)

[LogOutput With VComfort 0.1.0 Version new save.log](https://github.com/user-attachments/files/20507073/LogOutput.With.VComfort.0.1.0.Version.new.save.log)

**Comment by SkyKDG** [comment]
Ok so, in that Log I can see that the plugin is loading successfully but due to not being a debug version of my mod there's not much more info. So can you use this debug version of the mod and then run the server, log in with a player (this should trigger some logging) and then send me the new log. Can't directly upload the dll here so here's the download [link](https://gofile.io/d/BUhB1y)

**Comment by DiabloFan8675309** [comment]
Okay, I started off with a new save using VComforts 0.4.0. After confirming issues I closed everything out and swapped to the debug VComforts you sent. Here is that server LogOutput file.

[LogOutput.log](https://github.com/user-attachments/files/20507489/LogOutput.log)

**Comment by SkyKDG** [comment]
Ok so this helps a lot. It looks like the reset logic is not running while the new logic is running. But the new logic doesn't reset the old logic. I'm going to give you another debug version that will reset the logic on every action.

**Comment by SkyKDG** [comment]
Here's that version, this one should reset the values on split for all players even offline ones. So if u middle click in your inventory the inventories should be fixed, stack sizes will stay the same if the settings are enabled but the issues should no longer occur. [Download Here](https://gofile.io/d/pPN72U) feel free to send the logs again after this.

EDIT: be sure to remove the mod after this then!

**Comment by DiabloFan8675309** [comment]
I replaced the existing mod dll with the new one you provided. I can confirm this fixed the inventory issues. I then removed the mod issues remained fixed. I am going to run this on the server and see how things are, a lot more people testing everything else that was going on. I will update you once done.

**Comment by DiabloFan8675309** [comment]
When adding this to the online server it did not fix the issues.

https://streamable.com/drai3g

[LogOutput.log](https://github.com/user-attachments/files/20507935/LogOutput.log)

EDIT: looking at the log file, I see it was fixing everyone. Possible I didnt wait long enough for things to correct? Let me know if we should retry it or wait for an updated one.

**Comment by SkyKDG** [comment]
It gets stuck on a user that doesn't have a playercharacter yet and crashes, im adding an extra check in that should stop this from happening and hopefully it can fully complete the reset, uploading the file in a bit.

**Comment by DiabloFan8675309** [comment]
Okay cool, will try when you send it.

**Comment by SkyKDG** [comment]
Ok [here](https://gofile.io/d/eFjdFN) is the new file it first does a check to make sure the user isn't null or doesn't have a character. Feel free to send the logs again if there still might be an issue.

**Comment by DiabloFan8675309** [comment]
Good news, the majority of the issues have been solved - thank you!

We are still experiencing issues with fishing not working. You fish and do not get anything. This is also after the mod was removed too.

https://streamable.com/km4qu5

[LogOutput.log](https://github.com/user-attachments/files/20508575/LogOutput.log)

EDIT: It doesnt seem to be an issue for everyone just a select group.

**Comment by SkyKDG** [comment]
ah I see, ill have to look into that a bit more, maybe a buff that doesn't dissipate probably? Ill try uploading another updated version of the mod with a check to remove the fishing buff, i remember in an earlier version it would not apply it correctly but again I'm not sure if that will fix it.

**Comment by DiabloFan8675309** [comment]
Okay thank you, well try when things are ready to be tested.

**Comment by SkyKDG** [comment]
ok so this new version does all the previous resets on server startup but now also tries removing the catching buff from a player that has it which hopefully fixes that issue, because that is the only thing my autofishing mod basically does it adds the AB_Fishing_Draw_Buff to a player that is fishing. Download [here](https://gofile.io/d/ZHl3c7). it will check all players and see if they have a residual buff that may cause that.

**Comment by DiabloFan8675309** [comment]
Sadly this did not fix the fishing issues. Same as before, fish and nothing is caught.

**Comment by SkyKDG** [comment]
Ok then its not due to the buff, currently not sure what else could be causing it, will have to investigate more.

Edit:
All my fish code does is the following:
`BuffUtil.AddBuff(owner, Prefabs.AB_Fishing_Draw_Buff, 1);` Adds the draw buff for 1 second to the user.

Not sure if u can check the users that have the issue and list their buffs using kindredcommands. Maybe there's an extra buff that stays when it shouldn't?

**Comment by DiabloFan8675309** [comment]
I dont see this on their buff list. I was able to extract it with kindred extracts for you to see if this helps. 

[Player_Auriliah_937929_1.txt](https://github.com/user-attachments/files/20509267/Player_Auriliah_937929_1.txt)

**Comment by SkyKDG** [comment]
I've done a full analysis of all the components and the only thing I've noticed is the following:


### player with no issues has
```
player AttachedBuffer contains:
[109]    
PrefabGuid: AB_Fishing_Cast PrefabGuid(1010344901)
Entity: Entity AB_Fishing_Cast PrefabGuid(1010344901) - Entity(370553:1)

[110]
PrefabGuid: AB_Fishing_Draw_Cast PrefabGuid(-849143290)
Entity: Entity AB_Fishing_Draw_Cast PrefabGuid(-849143290) - Entity(370552:1)

[244]
PrefabGuid: AB_Fishing_Draw_AbilityGroup PrefabGuid(2122998237)
Entity: Entity AB_Fishing_Draw_AbilityGroup PrefabGuid(2122998237) - Entity(373037:1)

[247]
PrefabGuid: AB_Fishing_AbilityGroup PrefabGuid(-1016182556)
Entity: Entity AB_Fishing_AbilityGroup PrefabGuid(-1016182556) - Entity(373040:1)

player AbilityGroupSlotBuffer contains:
[96]
BaseAbilityGroupOnSlot: AB_Fishing_AbilityGroup PrefabGuid(-1016182556)
ShowOnBar: False
GroupSlotEntity: Entity AbilityGroupSlot PrefabGuid(-633717863) - NetworkedEntity(350947:1)
[97]
BaseAbilityGroupOnSlot: AB_Fishing_Draw_AbilityGroup PrefabGuid(2122998237)
ShowOnBar: False
GroupSlotEntity: Entity AbilityGroupSlot PrefabGuid(-633717863) - NetworkedEntity(351070:1)
```
### player with broken fishing has

```
player AttachedBuffer contains:
[229]
PrefabGuid: AB_Fishing_Cast PrefabGuid(1010344901)
Entity: Entity AB_Fishing_Cast PrefabGuid(1010344901) - Entity(820195:1)
[230]
PrefabGuid: AB_Fishing_Draw_Cast PrefabGuid(-849143290)
Entity: Entity AB_Fishing_Draw_Cast PrefabGuid(-849143290) - Entity(820194:1)


player AbilityGroupSlotBuffer contains:
[95]
BaseAbilityGroupOnSlot: AB_Fishing_AbilityGroup PrefabGuid(-1016182556)
ShowOnBar: False
GroupSlotEntity: Entity AbilityGroupSlot PrefabGuid(-633717863) - NetworkedEntity(818794:1)

[96]
BaseAbilityGroupOnSlot: AB_Fishing_Draw_AbilityGroup PrefabGuid(2122998237)
ShowOnBar: False
GroupSlotEntity: Entity AbilityGroupSlot PrefabGuid(-633717863) - NetworkedEntity(818841:1)
```

A player with the broken fishing is missing the `AB_Fishing_Draw_AbilityGroup` and the `AB_Fishing_AbilityGroup` inside of their `attachedBuffer`. 

This is a comparison between my character on my server and the player you sent above so if u can maybe send me data of a player that doesn't have an issue I can confirm that this is the issue then.

**Comment by DiabloFan8675309** [comment]
Here is an example of a player that does not have any issues fishing.

[Player_CopyRiot_940085_1.txt](https://github.com/user-attachments/files/20511945/Player_CopyRiot_940085_1.txt)

**Comment by DiabloFan8675309** [comment]
The fishing issue for this player was linked to a separate matter, which has now been resolved. We truly appreciate all your efforts in helping our issues!

**Comment by Raffled99** [comment]
Hello, recently I installed this mod then uninstalled it and ive had similar issues with the potions and stacks. Primarily, if i have a blood merlot (not from a prisoner) in my inventory, or a normal blood potion and then try to put one from a prisoner in my inventory, they either disappear or turn into a normal blood merlot/potion. Deleting the % blood thing you just got. Same from the blood mixer, if you mix something and then try to put it in your inventory, itll just delete it. Makes me not want to play my save lol

**Comment by cawphee-black** [comment]
I was going to open an issue about blood potions and blood merlots but I see this covers it.

As far as I know I have the latest version of this mod.

I'm running into the same issue with blood potions at least.
For example if I harvest 2 blood merlots then try to transfer them from the prisoner/cage to my inventory 1 of them often disappears. Then if I move the remaining one from one inventory slot to another it produces a blank blood merlot.
I also saw similar issues with the blood mixer generating  blank blood potions on moving mixed blood merlots in my inventory
I have client logging set to All but do not see any logging that seems like it applies or any errors either.
Unfortunately the "server fix" mod does not let you properly reconfigure the server side bepinex.cfg file because it ALWAYS overwrites it so I cannot get it to log "All" and last time I tried to manually copy mods to the server folder those mods did not work so something weird is happening. The gist of it is though that I cannot provide server side logging with "All" as the setting.

**Comment by SkyKDG** [comment]
Before uninstalling the mod it is best to disable the inventory and level setting so that the mod can reset the values to the default ones this wasn't possible in older versions as I oversaw that this could occur. The older version of the mod used to override the stack size override on each inventory slot and didn't check for certain consumables, which caused these issues. Version 0.1.0 doesn't use that method anymore it instead overrides the itemDataMap which holds all the itemData for each item. But it will still need to run once to reset the values. My apologies for the issues.

By default if ENABLE_LEVEL_BONUS or ENABLE_INVENTORY_BONUS is disabled it will respectively reset the values for those. For each player when they log in. I'll try working on version 0.1.1 which will reset the values on launch so that no players need to log in individually to get reset.

Sorry for the later reply but I was on holiday.

**Comment by magix39** [comment]
Jumping in a little late here to add my +1 to running into this. Seems you might you already know what the issue/fix is from your last reply. Not sure when you plan to update but would maybe going back to using <0.1.0, loading game, empty inventory, remove mod work or should we just wait for an update? 

Currently my inventory looks like a minefield with all these limits lol.

![Image](https://github.com/user-attachments/assets/88adebdb-21a3-4f53-a08e-3f21d6883e6b)

Edit: TO be clear I tested this by clicking items from slot 1 into the slot with a limit. My friend and I had removed this mod after moving some jewels around and they were either going missing or duplicating. For me at least when the dupe issue happened it was happening on those "bad" inventory slots.

Shift clicking or collecting all or sorting inventory by passed these hidden limits in my inventory shown above

**Comment by DiabloFan8675309** [comment]
Howdy, back again.

It appears that the mod is still causing lingering effects, now impacting jewel storages. We've noticed that jewels are stacking on top of each other, similar to the weapon stacking issue we experienced when the mod was first installed.

Workaround Fix: To resolve this, remove all gems and replace the jewel storage chest. It appears the mod may still impact jewel storages that existed when we first installed it.

Could you look into this and see if there's a way to address the issue? Not all users are on Discord, so many may not be aware of the workaround.

Thanks for your help!

Video links:
https://streamable.com/uw6ex7

https://streamable.com/gbm1bw 


EDIT: No other mod or changes were done since the last time we went over removing VComforts.

**Comment by Raffled99** [comment]
> Before uninstalling the mod it is best to disable the inventory and level setting so that the mod can reset the values to the default ones this wasn't possible in older versions as I oversaw that this could occur. The older version of the mod used to override the stack size override on each inventory slot and didn't check for certain consumables, which caused these issues. Version 0.1.0 doesn't use that method anymore it instead overrides the itemDataMap which holds all the itemData for each item. But it will still need to run once to reset the values. My apologies for the issues.
> 
> By default if ENABLE_LEVEL_BONUS or ENABLE_INVENTORY_BONUS is disabled it will respectively reset the values for those. For each player when they log in. I'll try working on version 0.1.1 which will reset the values on launch so that no players need to log in individually to get reset.
> 
> Sorry for the later reply but I was on holiday.

Hi so I think I need a few clarifications here. Where are the settings located? are you talking ingame or in the mod config? As well as does this mean I have to reinstall the version that had the issues to disable it and then remove it? Sorry for the questions im just a bit confused.
